name: Fetch LibCal Room Availability

on:
  workflow_dispatch:  # This lets you manually trigger it

jobs:
  get-availability:
    runs-on: ubuntu-latest

    steps:
      - name: Get Access Token from LibCal
        id: get_token
        run: |
          RESPONSE=$(curl -s -X POST https://lewistonlibrary.libcal.com/1.1/oauth/token \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.LIBCAL_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.LIBCAL_CLIENT_SECRET }}" \
            -d "grant_type=client_credentials")
          
          echo "RESPONSE: $RESPONSE"  # Log the raw response for debugging

          # Attempt to parse the access token
          TOKEN=$(echo $RESPONSE | jq -r '.access_token')
          
          # If no token is found, exit with an error
          if [ "$TOKEN" == "null" ]; then
            echo "Error: No access token received."
            exit 1
          fi

          echo "ACCESS_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Fetch Room Availability
        run: |
          curl -X GET "https://lewistonlibrary.libcal.com/1.1/space/availability" \
          -H "Authorization: Bearer $ACCESS_TOKEN"
