name: Fetch LibCal Events Every Hour

on:
  schedule:
    - cron: '0 * * * *'   # every hour on the hour
  workflow_dispatch:      # allows manual trigger

jobs:
  fetch-events:
    runs-on: ubuntu-latest

    steps:
      - name: Get Access Token from LibCal
        id: get_token
        run: |
          RESPONSE=$(curl -s -X POST "https://lewistonlibrary.libcal.com/1.1/oauth/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.LIBCAL_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.LIBCAL_CLIENT_SECRET }}" \
            -d "grant_type=client_credentials")
          echo "Response: $RESPONSE"
          TOKEN=$(echo $RESPONSE | jq -r '.access_token')
          if [[ -z "$TOKEN" || "$TOKEN" == "null" ]]; then
            echo "Failed to get token!"
            exit 1
          fi
          echo "ACCESS_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Fetch Events from LibCal
        run: |
          curl -X GET "https://lewistonlibrary.libcal.com/1.1/events?cal_id=21834" \
          -H "Authorization: Bearer $ACCESS_TOKEN" > events.json
          echo "Events saved to events.json"
          
      - name: Show first 300 characters of events
        run: |
          head -c 300 events.json


