name: Fetch LibCal Events Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # every hour on the hour
  workflow_dispatch:

jobs:
  fetch-events:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Access Token
        id: get_token
        run: |
          RESPONSE=$(curl -s -X POST "https://lewistonlibrary.libcal.com/1.1/oauth/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.LIBCAL_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.LIBCAL_CLIENT_SECRET }}" \
            -d "grant_type=client_credentials")
          TOKEN=$(echo $RESPONSE | jq -r '.access_token')
          if [[ -z "$TOKEN" || "$TOKEN" == "null" ]]; then
            echo "Failed to get token!"
            exit 1
          fi
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Fetch events and save to events.json
        run: |
          curl -s -X GET "https://lewistonlibrary.libcal.com/1.1/events?cal_id=21834" \
          -H "Authorization: Bearer $TOKEN" > events.json

      - name: Commit and push events.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add events.json
          git commit -m "Update events.json from LibCal"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
